### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mskelton** [ailohq/github-deployment-buildkite-plugin#1]
This repo is missing a license, which thus results in it having full copyright.  Would you consider adding a license to this repo?

From the [GitHub docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by jtomaszewski** [comment]
No problem. We will add mit license today.;)

**Comment by jtomaszewski** [comment]
Done: https://github.com/ailohq/github-deployment-buildkite-plugin/commit/e2fae44af04b673030a06c68117a28678640ff2b .

**Comment by mskelton** [comment]
Thanks a bunch for the quick response!
