### ISSUE TITLE
Add an option for propagating GITHUB_ environment vars

### ISSUE THREAD

**Issue by bluemalkin** [ailohq/github-deployment-buildkite-plugin#3]
This plugin only works if `GITHUB_TOKEN` is set as an env var which can only be set using the `env` yaml of the pipeline or using the agent set global env vars.

This means the token is hard-coded into the yaml which is anti pattern.

A good approach would be use something like `propagate-environment: true`  which this plugin uses: https://github.com/buildkite-plugins/docker-buildkite-plugin

Then I can run some commands which will fetch the GITHUB_TOKEN from my secrets manager.

Or are there other ways to pass the GITHUB_TOKEN in a secure way ?

**Comment by jtomaszewski** [comment]
What's the security risk here?

Please note: `token-env` option is not the token per-se. Instead, it's the name of an env variable from which token will be taken.

That environment variable can be set using [agent hook](https://buildkite.com/docs/agent/v3/hooks), which is something that the [buildkite official cloudformation stack for agents](https://github.com/buildkite/elastic-ci-stack-for-aws#build-secrets) is doing.

I think this is all quite secure; but feel free to point out how else it should be working.

**Comment by bluemalkin** [comment]
Thanks.
